CREATE PROC FI_SP_AltBeneficiario
    @CPF       VARCHAR(11),
    @NOME      VARCHAR(50),
    @IDCLIENTE BIGINT,
    @ID        BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		CPF = @CPF, 
		NOME = @NOME, 
		IDCLIENTE = @IDCLIENTE
	WHERE ID = @ID
END
